def PASSWORD = &USERNAME
--
def USER_TABLESPACE = USERS
--
def TEMP_TABLESPACE = TEMP
--
def DELETE_SCHEMAS = TRUE
--
def CREATE_TABLES  = TRUE 
--
def LOAD_INSTANCES = TRUE 
--
def LOCAL = TRUE
--
def BINARY_XML = TRUE
--
def REPOSITORY_USAGE = DBMS_XMLSCHEMA.ENABLE_HIERARCHY_NONE
--
-- def REPOSITORY_USAGE = DBMS_XMLSCHEMA.ENABLE_HIERARCHY_CONTENTS
--
-- def REPOSITORY_USAGE = DBMS_XMLSCHEMA.ENABLE_HIERARCHY_RESMETADATA
--
def DISABLE_DOM_FIDELITY = TRUE
--
def SCHEMA_FOLDER = ''
--
def TARGET_SCHEMA = ''
--
def SCHEMA_LOCATION_PREFIX = ''
--
