var DIGEST_AUTH_SCRIPT VARCHAR2(120);
--
declare
  V_DIGEST_AUTH_SCRIPT VARCHAR2(120);
begin
$IF DBMS_DB_VERSION.VER_LE_12_1 $THEN
  V_DIGEST_AUTH_SCRIPT := 'doNothing.sql';
$ELSE
  V_DIGEST_AUTH_SCRIPT := 'enableDigestAuth.sql';
$END
  :DIGEST_AUTH_SCRIPT := V_DIGEST_AUTH_SCRIPT;
end;
/
undef DIGEST_AUTH_SCRIPT
--
column DIGEST_AUTH_SCRIPT new_value DIGEST_AUTH_SCRIPT 
--
select :DIGEST_AUTH_SCRIPT DIGEST_AUTH_SCRIPT
  from dual
/
def DIGEST_AUTH_SCRIPT
--