DBA=$1
DBAPWD=$2
XFILES=$3
XFILESPWD=$4
XDBEXT=$5
XDBEXTPWD=$6
DEMOUSER=$7
DEMOPWD=$8
SERVERURL=$9
cd XFILES/install 
sh XFILES.sh $DBA $DBAPWD $XFILES $XFILESPWD $SERVERURL
cd ../../ImageMetadata/install
sh ImageMetadata.sh $DBA $DBAPWD $XDBEXT $XDBEXTPWD $SERVERURL
cd ../../EVOLUTION/install
sh EVOLUTION.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../GENERATION/install
sh GENERATION.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../INTRODUCTION/install
sh INTRODUCTION.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../PARTITIONING/install
sh PARTITIONING.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../XQUERY/install
sh XQUERY.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../FULLTEXT-LITE/install
sh FULLTEXT-LITE.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../NVPAIR/install
sh NVPAIR.sh $DBA $DBAPWD $DEMOUSER $DEMOPWD $SERVERURL
cd ../../..
